Changes in the output handling and some configs
TehNut-Mods/ResourcefulCrops pull request #38
Opened 2016-11-03 18:53 UTC by ceiphas

- Added config values for defaults: extra seed chance, essence drop chance, shard crafting recipe
- Changed the handling of the output from three hard coded recipes to an open format, supporting unlimited recipes per shard

the changes were tested with old and new seed files, and should be fully backward compatible

2016-11-03 19:25 UTC, TehNut commented
After a once-over on my phone, this looks good. Will look over a bit more when I get home

2016-11-03 21:03 UTC, TehNut requested changes

2016-11-03 21:03 UTC, TehNut commented on src/main/java/tehnut/resourceful/crops/api/base/Output.java
> +    private static final Pattern linePattern   = Pattern.compile("^[S ]{2,3}$");
Not a fan of the whitespacing for these fields

2016-11-03 21:03 UTC, TehNut commented on src/main/java/tehnut/resourceful/crops/api/base/OutputBuilder.java
> +    private String    recipe = "default";
Whitespacing

2016-11-03 21:03 UTC, TehNut commented on src/main/java/tehnut/resourceful/crops/registry/RecipeRegistry.java
> +	                		GameRegistry.addRecipe(new ShapedOreRecipe(
Spacing

2016-11-03 21:03 UTC, TehNut commented on src/main/java/tehnut/resourceful/crops/api/base/Output.java
> +                if ("default".equals(recipe[0])) {
How about making these an enum and using `Enum#valueOf(recipe [0]).getRecipe()`

2016-11-03 21:11 UTC, ceiphas commented on src/main/java/tehnut/resourceful/crops/api/base/Output.java
> +                if ("default".equals(recipe[0])) {
Problem is, that 2x2 is not a valid Enum value, as is 3x3...

2016-11-03 21:11 UTC, ceiphas commented on src/main/java/tehnut/resourceful/crops/api/base/Output.java
> +    private static final Pattern linePattern   = Pattern.compile("^[S ]{2,3}$");
sorry, i'll tell my eclipse to remove that

2016-11-03 21:11 UTC, ceiphas commented on src/main/java/tehnut/resourceful/crops/api/base/OutputBuilder.java
> +    private String    recipe = "default";
sorry, i'll tell my eclipse to remove that

2016-11-04 03:40 UTC, TehNut approved these changes

2016-11-04 03:41 UTC, TehNut commented
I pushed some commits I forgot I had locally. If you resolve the conflicts, I will merge. Sorry!

2016-11-04 16:11 UTC, merged